spring:
  application:
    name: Badge-and-Membership-System


  datasource:
    url: jdbc:sqlserver://cs544.cs.miu.edu:1433;databaseName=CS544-202303-10;encrypt=true;trustServerCertificate=true;
    username: CS544-202303-10
    password: 721e7737-9abb-4c18-bd63-4d48f5048a7d
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      maximumPoolSize: 10


  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: create-drop

    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2016Dialect
        show-sql: true
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
server:
  port: 8085

logging:
  level:
    root: ERROR

